var namespaceswagger__client_1_1api_1_1recherche__de__cours__api =
[
    [ "RechercheDeCoursApi", "classswagger__client_1_1api_1_1recherche__de__cours__api_1_1_recherche_de_cours_api.html", "classswagger__client_1_1api_1_1recherche__de__cours__api_1_1_recherche_de_cours_api" ]
];